### ISSUE TITLE
Disclaimer shows up on other disputes even those I already clicked "I understand"

### ISSUE THREAD

**Issue by john-light** [aragon/court-dashboard#299]
See how the disclaimer shows up on another dispute even though I clicked "I understand" and made it disappear on the first dispute.

![Screenshot_2020-04-28 Aragon Court Dashboard(1)](https://user-images.githubusercontent.com/9424721/80499635-3c8a6500-893b-11ea-8c75-fa764b726425.png)

![Screenshot_2020-04-28 Aragon Court Dashboard](https://user-images.githubusercontent.com/9424721/80499651-3f855580-893b-11ea-9602-81f7052bec6a.png)

**Comment by sohkai** [comment]
This is intended for now—we may update this behaviour if we place a visual indicator in each dispute to mark it as being part of the precedence campaign.

We've done this in the event that a "normal" dispute occurs, so that a user is warned on each dispute whether it is part of the precedence campaign or not.
